-- data:extend({
-- 	{
-- 		type = "bool-setting",
-- 		name = "planet-hopper-can-launch-to-planets-with-surface",
-- 		setting_type = "runtime-global",
-- 		default_value = true,
-- 		order = "a",
-- 	},
-- })
